# Generated by Django 5.2.4 on 2026-06-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('escenario', models.CharField(max_length=50)),
                ('masa', models.FloatField()),
                ('fuerza', models.FloatField()),
                ('friccion', models.FloatField()),
                ('aceleracion_promedio', models.FloatField()),
                ('tiempo_total', models.FloatField()),
                ('distancia_recorrida', models.FloatField()),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
