# Generated by Django 5.2.4 on 2026-06-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationrecord',
            name='tiempo_total',
        ),
        migrations.AddField(
            model_name='simulationrecord',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationrecord',
            name='clima',
            field=models.CharField(default='Seco', max_length=30),
        ),
        migrations.AddField(
            model_name='simulationrecord',
            name='resistencia_aire',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='simulationrecord',
            name='velocidad_inicial',
            field=models.FloatField(default=0),
        ),
    ]
