# Generated by Django 5.2.4 on 2026-06-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_api', '0002_remove_simulationrecord_tiempo_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrecord',
            name='tiempo_total',
            field=models.FloatField(default=0.0),
        ),
    ]
