# Generated by Django 5.2.4 on 2026-06-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_api', '0003_simulationrecord_tiempo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrecord',
            name='inclinacion',
            field=models.FloatField(default=0.0),
        ),
    ]
