# Generated by Django 5.2.4 on 2026-06-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_api', '0004_simulationrecord_inclinacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrecord',
            name='friccion_estatica',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationrecord',
            name='masa_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationrecord',
            name='perfil_fuerza',
            field=models.CharField(default='Constante', max_length=30),
        ),
    ]
