# Generated by Django 5.2.4 on 2026-07-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_api', '0005_simulationrecord_friccion_estatica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrecord',
            name='modo',
            field=models.CharField(default='Aceleracion', max_length=20),
        ),
        migrations.AddField(
            model_name='simulationrecord',
            name='sustentacion_coef',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
